version: "2"
services:
  postgresql:
    image: postgres
    networks:
      - sonarnetwork
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  sonar:
    image: sonarqube:8.2-community
    ports:
      - "80:9000"
    depends_on:
      - postgresql
    ulimits:
     nofile:
      soft: 65535
      hard: 65535 
    networks:
      - sonarnetwork
    environment:
      - sonar.jdbc.url=jdbc:postgresql://postgresql:5432/sonar
      - sonar.web.javaOpts=-server -Xms1g -Xmx2g -XX:+HeapDumpOnOutOfMemoryError
      - sonar.ce.javaOpts=-Xms4g -Xmx4g -XX:+HeapDumpOnOutOfMemoryError
      - sonar.search.javaOpts=-Xms2g -Xmx2g -XX:+HeapDumpOnOutOfMemoryError
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
networks:
  sonarnetwork:
    driver: bridge
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
